services:
  db:
    image: postgres:15
    container_name: hospital-db
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: hospital_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5050:5432"
    volumes:
      - hospital_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hospital_network
volumes:
  hospital_data:

networks:
  hospital_network:
    driver: bridge