version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hospital-db
    env_file:
      - ./.env
    restart: always
    environment:
      POSTGRES_DB: hospital_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5050:5432"
    volumes:
      - hospital_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hospital_network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-auth-service
    container_name: auth-service
    env_file: ./.env
    ports:
      - "8091:8091"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  admin-service:
    build:
      context: .
      dockerfile: Dockerfile-admin-service
    container_name: admin-service
    env_file: ./.env
    ports:
      - "8090:8090"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  consulting-service:
    build:
      context: .
      dockerfile: Dockerfile-consulting-service
    container_name: consulting-service
    env_file: ./.env
    ports:
      - "8092:8092"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  report-service:
    build:
      context: .
      dockerfile: Dockerfile-report-service
    container_name: reporting-service
    env_file: ./.env
    ports:
      - "8093:8093"
    networks:
      - hospital_network
    depends_on:
      - db
      - eureka-server

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile-hospital-eureka-server
    container_name: eureka-server
    env_file: ./.env
    ports:
      - "8761:8761"
    networks:
      - hospital_network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile-hospital-gateway
    container_name: gateway
    env_file: ./.env
    ports:
      - "8080:8080"
    networks:
      - hospital_network
    depends_on:
      - auth-service
      - admin-service
      - consulting-service
      - report-service
      - eureka-server

volumes:
  hospital_data:

networks:
  hospital_network:
    driver: bridge
