spring:
  cloud:
    gateway:
      routes:
        # ====== DOCS primero (reescritura SOLO para /v3/api-docs) ======
        - id: auth-service-docs
          uri: ${GATEWAY_URI_AUTH_SERVICE}
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<seg>v3/api-docs.*), /${seg}

        - id: consulting-service-docs
          uri: ${GATEWAY_URI_CONSULTING_SERVICE}
          predicates:
            - Path=/api/consulting/v3/api-docs
          filters:
            - RewritePath=/api/consulting/(?<seg>v3/api-docs.*), /${seg}

        - id: admin-service-docs
          uri: ${GATEWAY_URI_ADMIN_SERVICE}
          predicates:
            - Path=/admin/v3/api-docs
          filters:
            - RewritePath=/admin/(?<seg>v3/api-docs.*), /${seg}

        - id: report-service-docs
          uri: ${GATEWAY_URI_REPORTING_SERVICE}
          predicates:
            - Path=/api/report/v3/api-docs
          filters:
            - RewritePath=/api/reports/(?<seg>v3/api-docs.*), /${seg}

        # ====== TRÁFICO NORMAL (sin StripPrefix) ======
        - id: auth-service
          uri: ${GATEWAY_URI_AUTH_SERVICE}
          predicates:
            - Path=/auth/**

        - id: consulting-service
          uri: ${GATEWAY_URI_CONSULTING_SERVICE}
          predicates:
            - Path=/api/consulting/**

        - id: admin-service
          uri: ${GATEWAY_URI_ADMIN_SERVICE}
          predicates:
            - Path=/admin/**

        - id: report-service
          uri: ${GATEWAY_URI_REPORTING_SERVICE}
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: consulting-service
        url: /api/consulting/v3/api-docs
      - name: admin-service
        url: /admin/v3/api-docs
      - name: reporting-service
        url: /api/reports/v3/api-docs # <-- corregido (antes decía /reportes)
